server:
  port: 8888

spring:
  application:
    name: server-config
  #profiles:
    #active: native
  cloud:
    config:
      server:
        #native:
          #search-locations: file:///cma/009_MiniUber/02Desarrollo/09Fuentes/server-config/properties
        git:
          uri: https://git-codecommit.us-east-2.amazonaws.com/v1/repos/server-properties
          username: SoftProgiGit-at-806200091356
          password: F2zzujVUYj07T4szUdJ9qdl29KTnqdGcmm8qXMGXSz4=
      label: master