server:
  port: 8888

spring:
  application:
    name: softprogy-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///server/config
        #git:
          #uri: https://git-codecommit.us-east-2.amazonaws.com/v1/repos/kacera-config
          #username: SoftProgiGit+1-at-806200091356
          #password: 0ThDenGmcn00BLLIwgQaMPzaIjom6P5eP9avz6JMulc=
      label: master